### PR TITLE
guide: MP Guide maintenance backlog

### PR DESCRIPTION
**Pull request by Zweihorn**
This PR is a **DRAFT** and _work in progress (**WIP**)_

The Guide provides excellent advice and is one of the main entry points for MacPorts beginners.

However, IMO quite obviously **the MP Guide needs QA** and more continuity in maintenance to the text of the guide itself.

This PR:
1. Provides the **Backlog** list - ref https://github.com/macports/macports-guide/pull/53#issuecomment-1374804353
2. The former commits are found to be misled unfortunately.

However, any consideration and further advice would be highly appreciated.

### CODE REVIEW

**Comment by Zweihorn** [comment]
# Backlog:

## Improve

IMO the _MacPorts Guide_ could improve from **quality assurance**.  Nevertheless the Guide provides excellent advice.

**WIP** - This PR and this Comment could become a **standing document** until further notice, I presume.

This PR might not be fully compatible to but certainly is related to [7.5. Updating Documentation](https://guide.macports.org/#project.docs)

### Amend

Amending **missing content** at:

#### New section on 'subport'

AFAIK the [Chapter 4. Portfile Development](https://guide.macports.org/#development) lacks sufficient documentary on the 'subport' excellent opportunities both for new Portfile development and port mainentance, unfortunately.

#### section [4.7. Portfile Best Practices](https://guide.macports.org/#development.practices)
  - [4.7.2. Don't Overwrite Config Files](https://guide.macports.org/#development.practices.dont-overwrite)
    TODO:
  - [4.7.3. Install Docs and Examples](https://guide.macports.org/#development.practices.install-docs)
    TODO:
  - [4.7.4. Provide User Messages](https://guide.macports.org/#development.practices.provide-messages)
    TODO:
  - [4.7.5. Use Variables](https://guide.macports.org/#development.practices.use-variables)
   TODO: Set variables so changing paths may be done in one place; use them anytime it makes updates simpler: `distname ${name}-src-${version}`

#### section [5.6. Tcl Extensions & Useful Tcl Commands](https://guide.macports.org/#reference.tcl-extensions)

  > **External program execution**
  >
  > Use only when ....

#### section [6.1. File Hierarchy](https://guide.macports.org/#internals.hierarchy)
  > [PORTHIER](https://guide.macports.org/#porthier)
  > — layout of the ports filesystems
  > Name
  > porthier — layout of the ports filesystems

#### harmonisation of sections 7.1 & 7.3

##### section [7.1. Using Trac for Tickets](https://guide.macports.org/#project.tickets)

> The MacPorts Project uses a system called [Trac](https://trac.macports.org/) to file tickets to report bugs and enhancement requests. Though anyone may search Trac for tickets, you must have a [GitHub account](https://github.com/join) in order to login to [Trac](https://trac.macports.org/) to create tickets.

ADD: _The GitHub pull request method is strongly preferred over submitting Trac tickets._

##### section [7.3. Contributing to MacPorts](https://guide.macports.org/#project.contributing)
> You may contribute new ports and enhancements of any kind to already existing ports using Trac tickets. However, we prefer that you open a pull request on [GitHub](https://github.com/macports/macports-ports/pulls), in which case no Trac ticket is required.
>
> **The GitHub pull request method is strongly preferred over submitting Trac tickets. Submitting a Pull Request will likely result in your contribution being merged into MacPorts much faster, as the workflow is much easier for the maintainers.**

#### Extend 8. Glossary from the utter stub

##### [Chapter 8. MacPorts Guide Glossary](https://guide.macports.org/#guide-terms)

##### [Glossary](https://guide.macports.org/#glossary)

> This section defines a number of words which may be new to the reader. These are all defined in the context of Macports instead of as general purpose definition.

However, **does not meet the expectations** of the reader who would welcome a true glossary and not a stub with a list of terms mostly if not all remaining rather unexplained.

#### TBD

TBC

## Continuity

For the former _Backlog_ and some of my notes on this documentary trials as of:
- [2023-01-08](https://github.com/Zweihorn/Zweihorn_fascicle/blob/main/mynotes_mp_by-date/mynotes_mp_2023-01-08c.md)
- _tbc_

Ignorance is a bliss. Learning and improving is fun.

NOTE: Found nothing reasonable on how to wrap long texts and like my notes more located in my domain anyway.

Hope this helps.

🌻

**Comment by Zweihorn** [comment]
Found something on 'subports' at
- https://trac.macports.org/ticket/36957

**Comment by Zweihorn** [comment]
THX - Apparently, it helped me to do my job as new maintainer of some little port called [minetest](https://forum.minetest.net/viewtopic.php?p=419980&sid=47f156040b2f51cfc32c8e951e7d666f#p419980).

If you like, have a look at my funny ideas of new **subport definitions** as Portfile amend in my first draft release at: 
- WIP and moving target - stay tuned

Have fun.

**Comment by Zweihorn** [comment]
Amend:

#### section [5.6. Tcl Extensions & Useful Tcl Commands](https://guide.macports.org/#reference.tcl-extensions)

  > **External program execution**
  >
  > Use only when ....

**Comment by raimue** [comment]
I am not quite sure I understand what this PR is about. But as I see you mentioned the `adoc/` directory, please note that this was auto-generated from the DocBook XML at some point in the past (last time 2020). All changes to `adoc/` will be lost when the conversion scripts runs again, so all updates for the guide should only be made to the DocBook XML.

I added the AsciiDoc conversion in the past to attract more interest and help for the conversion, but it did not gain more traction. I actually think it should be deleted from the repository at this point, because it is more confusing than it does help. I am sorry for this mess.

More information can be found in the corresponding ticket for the AsciiDoc conversion:
https://trac.macports.org/ticket/56046#comment:3

**Comment by Zweihorn** [comment]
> I am not quite sure I understand what this PR is about. But as I see you mentioned the `adoc/` directory, please note that this was auto-generated from the DocBook XML at some point in the past (last time 2020). All changes to `adoc/` will be lost when the conversion scripts runs again, so all updates for the guide should only be made to the DocBook XML.
> 

Good to know and I will disband my misled work on adoc/ accordingly.

However, please consider my volunteering  preliminary role at https://trac.macports.org/ticket/36957#comment:19

> I added the AsciiDoc conversion in the past to attract more interest and help for the conversion, but it did not gain more traction. I actually think it should be deleted from the repository at this point, because it is more confusing than it does help. I am sorry for this mess.
> 

Understood. Anyway a good learning experience and I am seeking to make myself more familiar with MacPorts and the MacPorts Guide anyway.

> More information can be found in the corresponding ticket for the AsciiDoc conversion: https://trac.macports.org/ticket/56046#comment:3

I will consider in adding my a.m. **Backlog** content into your a.m. trac ticket or the b.m. trac ticket or another new trac ticket in due time.
- https://github.com/macports/macports-guide/pull/53#issuecomment-1374804353
- https://trac.macports.org/ticket/36957

Furthermore, IMO the Guide was somewhat unclear if MacPorts prefers GitHub (lacking Issue availability apparently) over Trac tickets or not.

THX - First things first and I will accomplish my work on _subport_ amendments to 'minetest' before furthering this PR.

**Pull request closed without merging**
