### PR TITLE
Clarify usage of the epoch keyword

### PR DESCRIPTION
**Pull request by ra1nb0w**

### CODE REVIEW

**Comment by mojca** [comment]
I would merge it immediately, but if nitpicking: could you please separate whitespace changes into a separate commit?

**Comment by ra1nb0w** [comment]
done

**Comment by mojca** [comment]
Oh, wait.

This is a temporary attempt to convert the guide to adoc and we might loose this text unless we either complete the conversion first or modify the corresponding xml file as well.

**Comment by ra1nb0w** [comment]
I also did the change on the xml file. Just to understand correctly: are you transitioning the macports guide from xml to adoc therefore a the end will be only adoc as main format?

**Comment by mojca** [comment]
Yes, the idea is to get rid of `xml`, at least as the source format (we might temporarily still use it as an intermediate format to generate documentation in pdf, but in that case it would be generated rather than considered the source). There's a readme inside `adoc`. There are still issues preventing us from doing the complete transition, not sure if anyone is actively working on any of those issues at the moment though.

**Comment by mojca** [comment]
Thank you (next time you might want to submit from your branch different from `master`).

**Comment by ra1nb0w** [comment]
> Thank you (next time you might want to submit from your branch different from `master`).

I know and in macports-ports I use branch but in this case is one shot and then remove ;-)
thank you

**Pull request merged**
