### PR TITLE
Update documentation for livecheck

### PR DESCRIPTION
**Pull request by dgilman**
Add documentation for livecheck.ignore_sslcert and livecheck.compression

See https://github.com/macports/macports-base/pull/167

### CODE REVIEW

**Comment by pmetzger** [comment]
Seems fine to me.

**Comment by raimue** [comment]
`livecheck.compression` is a new feature which is not yet in any release. This should not yet go directly to guide.macports.org. As described in the README, we should put that on a release-X.Y branch now and only merge it to master once it has been released.

**Comment by mascguy** [comment]
> `livecheck.compression` is a new feature which is not yet in any release. This should not yet go directly to guide.macports.org. As described in the README, we should put that on a release-X.Y branch now and only merge it to master once it has been released.

It would be great to retain the additions for `livecheck.ignore_sslcert` - and preferably merge them ASAP - as that option is handy when using legacy macOS releases.

**Comment by dgilman** [comment]
I also don't think there's anything preventing this PR from getting merged.

**Comment by mascguy** [comment]
> I also don't think there's anything preventing this PR from getting merged.

Agreed. And given that `livecheck.compression` has been in the wild since v2.7.0 - released 18-ish months ago - I think it's time we publish the documentation for it. Ditto for `livecheck.ignore_sslcert`.

Merging.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Ah, it's great to finally have this in the wild. Love it!

Docs - LiveCheck Additions

**Pull request merged**
