### PR TITLE
Redirect readers to local manual for full list

### PR DESCRIPTION
**Pull request by FranklinYu**
Actually I was going to add `load`, `unload` and `reload` actions, but I think the local manual is more up-to-date. I might append brief description for those actions later…

### CODE REVIEW

**Comment by ryandesign** [comment]
FYI "port help *whatever*" does the same thing as "man port-*whatever*" and we do have online versions of the manpages at https://man.macports.org. I don't know if we're already linking to the online manpages from the guide, but we might want to start doing that. We do want all commands to be findable in the guide, but we shouldn't need to write more than one copy of the text. Perhaps ideally the manpages would be an appendix of the guide, but we don't have the automated tooling to make that happen yet, and perhaps first we should complete the long-planned migration of the guide from docbook xml to asciidoc so that any automatic adding of manpages only has to be done once in asciidoc.

**Comment by FranklinYu** [comment]
Are we still migrating from DocBook to AsciiDoc? I thought the migration has stalled. If it’s still desired, I think we can have a CI to force PR authors to change corresponding AsciiDoc files when they touches the XML ones. I can make another PR to set up that CI. How do you like this idea?

**Comment by ryandesign** [comment]
As far as I know, yes, we still want to move to asciidoc, and yes, nothing has happened about that in awhile. I don't think we need any CI to ask users to modify both sets of files; instead, we want there to be only one set of files. Currently, that one set is docbook. In the future hopefully that one set will be asciidoc.

**Comment by raimue** [comment]
There is no need to update AsciiDoc right now, because all of it is generated from the DocBook XML. It is only checked in for convenience as running `docbookrx` for the conversion is not trivial and requires custom patches.

See: https://github.com/macports/macports-guide/blob/master/guide/adoc/README.md

**Comment by FranklinYu** [comment]
Do we plan to do any manual review after converting using our version of `docbookrx`? Or we should keep improving `docbookrx` until it perfectly converts our DocBook to AsciiDoc? (At which time we can simply do a one-shot final conversion before we completely shift to AsciiDoc as canonical.)

I know some Ruby, and might be able to help improving our fork of `docbookrx` if there is any issue in it.

Edit: Now I see there is a TODO section… Let me check what I can do about it.

**Comment by raimue** [comment]
The conversion with docbookrx isn't perfect and will need manual work as briefly outlined in the README. Of course this is only what I could spot. In February I put the AsciiDoc converted version on the guide-test subdomain for comparison and review: 
* https://lists.macports.org/pipermail/macports-dev/2020-February/041674.html
* https://lists.macports.org/pipermail/macports-dev/2020-February/041688.html

I think we should not continue too far from the original topic of this pull request. I suggest we move further discussion to macports-dev or chat.

**Comment by FranklinYu** [comment]
I agree. I force-pushed with a link to the online manual, since it doesn’t seem a lot of trouble to incoperate this update into our AsciiDoc source tree. We could continue the conversation about AsciiDoc conversion [elsewhere](https://trac.macports.org/ticket/56046).

**Review by raimue — APPROVED** [review]

**Review by mascguy — APPROVED** [review]
LGTM. Anyone else?

**Comment by mascguy** [comment]
Changes approved by @raimue on 2020-06-09, and looks reasonable. Merging.

**Pull request merged**
