### PR TITLE
Prefer https over http

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by grimreaper** [comment]
wait a sec - might have broken something

**Comment by grimreaper** [comment]
fixed. Despite the files existing with identical content, it doesn't build....

**Comment by jmroot** [comment]
- Why the change to the image?
- Did you check that all these sites do in fact support https?
- The portgroup documentation should reflect what the portgroups actually do, and these ones don't currently use https for the homepage.

**Comment by grimreaper** [comment]
- I'm not sure why the image is changing. There isn't any automated change here
- yes I did, went to each one and ensured it returned the same content. This is why not all URLs are modified.
- was going to going to and modify the PortGroup next...

**Comment by grimreaper** [comment]
ref macports/macports-ports#1011

**Comment by grimreaper** [comment]
@mf2k please also merge this :)

**Pull request merged**
