### PR TITLE
Bump jquery from 2 to 3

### PR DESCRIPTION
**Pull request by grimreaper**
While here use a CDN for jquery that users are likely to have cached.
This tradeoffs a very minor amount of control for making things faster for users (mostly on slow links, but latency in general).

FWIW the featureset enabled by jquery here is minimal and could likely be achieved by CSS alone AFAICT

### CODE REVIEW

**Comment by neverpanic** [comment]
At the moment, the guide works without loading resources from URLs outside of MacPorts' control. I'm not sure that we should allow Google to track users of the guide.

I'd welcome opinions on that, @raimue, @ryandesign, @jmroot.

**Comment by grimreaper** [comment]
FTR I'm not really opposed to adding a copy of a newer jquery. That said
- Google tracking CDN downloads isn't really much of a concern
- Performance for first time visitors on slow connections is a concern (though similarly, not huge)

**Comment by raimue** [comment]
I would rather avoid the Google CDN if possible. If size is really that much of an issue, we could probably have the same functionality without a full-blown jQuery framework...

**Comment by ryandesign** [comment]
If we can make do without jQuery, fine. If not, using a CDN has advantages. If we object to all CDNs, then use a locally-hosted copy. But if we only object to the Google CDN, how about using [jsDelivr](https://www.jsdelivr.com), which is also hosted by StackPath just like the MacPorts web sites.

**Comment by grimreaper** [comment]
I'm happy to do whatever, just figured it would be easier to use the CDN. If y'all tell me what to do, I'll do it :)

**Comment by grimreaper** [comment]
Changed PR to keep jquery local.

**Comment by neverpanic** [comment]
Thanks, but I don't see you adding the new version of jQuery. Did you forget that?

I can also be persuaded to live with jsDelivr.

**Comment by grimreaper** [comment]
"git add" is hard. fixed.

**Pull request merged**
